// <auto-generated />
namespace DepartmentManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initialDatabaseCreationV10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialDatabaseCreationV10));
        
        string IMigrationMetadata.Id
        {
            get { return "201912070422079_initialDatabaseCreation-V1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
